on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
# Installs Node and the npm packages saved in your package.json file in the build
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 18.x
        
    - name: install ADF Utilities package
      run: npm install
      working-directory: ${{github.workspace}}/testing-adf/build  # (1) provide the folder location of the package.json file
        
# Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
    - name: Validate
      run: npm run build validate ${{github.workspace}}/testing-adf/ /subscriptions/2e365525-e37e-43da-b869-8a4cc427db0b/resourceGroups/parthu-rg/providers/Microsoft.DataFactory/factories/parth-adf-testing # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 
      working-directory: ${{github.workspace}}/testing-adf/build
 

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}}/testing-adf /subscriptions/2e365525-e37e-43da-b869-8a4cc427db0b/resourceGroups/parthu-rg/providers/Microsoft.DataFactory/factories/parth-adf-testing "ExportedArmTemplate"  # (3) The build command, as validate, needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance. The 3rd parameter is the exported ARM template artifact name 
      working-directory: ${{github.workspace}}/testing-adf/build
 
# In order to leverage the artifact in another job, we need to upload it with the upload action 
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ExportedArmTemplate # (4) use the same artifact name you used in the previous export step
        path: ${{github.workspace}}/testing-adf/build/ExportedArmTemplate
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
 # we 1st download the previously uploaded artifact so we can leverage it later in the release job     
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ExportedArmTemplate # (5) Artifact name 


      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: parthu-rg # (6) your target ADF resource group name
          dataFactoryName: parthu-adf-qa # (7) your target ADF name
          armTemplateFile: ARMTemplateForFactory.json # (8) ARM template file name ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json # (9) ARM template parameters file name ARMTemplateParametersForFactory.json
          #additionalParameters: parthu-adf-qa # (10) Parameters which will be replaced in the ARM template. Expected format 'key1=value key2=value keyN=value'. At the minimum here you should provide the target ADF name parameter. Check the ARMTemplateParametersForFactory.json file for all the parameters that are expected in your scenario

         - name: ADF triggers stop --> Deployment and triggers start step
           uses: azure/powershell@v1
           with:
             inlineScript: |
            $ResourceGroupName = "${{ vars.DEFAULT_PROPERTIES_RESOURCEGROUP_VALUE1 }}" 
            $DataFactoryName = "${{ vars.FACTORYNAME1 }}"
            $Annotations = "LDS" 
            $Triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactoryName
            $stoppedTriggers = $Triggers | Where-Object { $_.Properties.RuntimeState -eq "Stopped" }
            $startedTriggers = @()
            
            foreach ($trigger in $Triggers) {
             if(($Trigger.Properties.Annotations[0] -eq $Annotations) -and ($Trigger.Properties.RuntimeState -eq "Started"))
                {
            # Stop the Triggers that were in "Started" state
            Stop-AzDataFactoryV2Trigger -ResourceGroupName $resourceGroupName -DataFactoryName $dataFactoryName -Name $trigger.Name -Force
            $startedTriggers += $trigger.Name
            Write-Host "Stopped trigger $($trigger.Name)."
            } elseif ($trigger.Triggerstate -eq "Stopped") {
                Write-Host "Trigger $($trigger.Name) is already in a stopped state."
            } else {
                Write-Host "Trigger $($trigger.Name) is in an unknown state: $($trigger.Triggerstate)."
            }
            }

            $password = ConvertTo-SecureString "${{ secrets.SPN_CERT_PASSWORD }}" -asplaintext -force
            Connect-AzAccount -ApplicationId "${{ secrets.SPN_CLIENT_ID }}" -Tenant "${{ secrets.SPN_TENANT_ID }}"  -CertificatePath '/home/runner/work/_temp/spn.pfx' -CertificatePassword $password 
            Set-AzContext -Subscription "${{ secrets.SPN_SUBSCRIPTION_ID }}"
            New-AzResourceGroupDeployment -ResourceGroupName ${{ vars.DEFAULT_PROPERTIES_RESOURCEGROUP_VALUE1 }} -TemplateFile "/home/runner/work/GithubRepostore/GithubRepostore/drop/ARMTemplateForFactory.json" -TemplateParameterFile "/home/runner/work/GithubRepostore/GithubRepostore/drop/ARMTemplateParametersForFactory.json"

            # Start the Triggers that were in "Started" state before stopping
            foreach ($triggerName in $startedTriggers) {
                Start-AzDataFactoryV2Trigger -ResourceGroupName ${{ vars.DEFAULT_PROPERTIES_RESOURCEGROUP_VALUE1 }} -DataFactoryName ${{ vars.FACTORYNAME1 }} -Name $triggerName -Force
                Write-Host "Started trigger $triggerName."
            }

            Write-Host "Trigger stop, Deployment and start step has been completed."
          azPSVersion: 'LatestVersion'
           if: success()
